### ISSUE TITLE
create-native-app throws error.

### ISSUE THREAD

**Issue by Necmttn** [ericvicenti/create-react-workspace#7]
here's the error.

```
npm run create-native-app native

> @ create-native-app /Users/necmettinkarakaya/Projects/workspace
> react-workspace-scripts create-native-app "native"

Creating native app Native at ./native
Installing dependencies, this may take a minute.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn react-native ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

**Comment by Necmttn** [comment]
alright, it's turnout I didn't have `react-native-CLI` that's why it throws this error.
